# Generated by Django 5.0.4 on 2024-04-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_name',
            field=models.CharField(default='', max_length=50, verbose_name='адрес ссылки'),
            preserve_default=False,
        ),
    ]
